// <auto-generated />
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Harvey.PIM.Application.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Harvey.PIM.Application.Infrastructure.CatalogMigrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20181130071430_add_price_model")]
    partial class add_price_model
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Harvey.PIM.Application.Infrastructure.Domain.Catalog.CatalogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.None);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Harvey.PIM.Application.Infrastructure.Domain.Catalog.CatalogFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CorrelationId");

                    b.Property<Guid>("EntityId");

                    b.Property<Guid>("FieldId");

                    b.Property<string>("FieldName");

                    b.Property<int>("FieldType");

                    b.Property<string>("FieldValue");

                    b.Property<Guid>("FieldValueId");

                    b.Property<bool>("IsVariantField");

                    b.Property<int>("OrderSection");

                    b.Property<string>("Section");

                    b.HasKey("Id");

                    b.ToTable("FieldValues");
                });

            modelBuilder.Entity("Harvey.PIM.Application.Infrastructure.Domain.Catalog.CatalogPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.None);

                    b.Property<float>("ListPrice");

                    b.Property<float>("MemberPrice");

                    b.Property<float>("StaffPrice");

                    b.HasKey("Id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Harvey.PIM.Application.Infrastructure.Domain.Catalog.CatalogProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.None);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Harvey.PIM.Application.Infrastructure.Domain.Catalog.CatalogVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.None);

                    b.Property<Guid>("PriceId");

                    b.Property<Guid>("ProductId");

                    b.HasKey("Id");

                    b.ToTable("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
